# Generated by Django 3.0.8 on 2020-07-20 13:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='testText',
            field=models.CharField(default='12', max_length=1),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 13, 3, 30, 2095, tzinfo=utc)),
        ),
    ]
