# Generated by Django 3.0.8 on 2020-07-20 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20200720_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='testText',
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 13, 4, 27, 956415, tzinfo=utc)),
        ),
    ]
