# Generated by Django 3.0.8 on 2020-07-21 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20200720_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='titleDesc',
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 12, 39, 26, 249132, tzinfo=utc)),
        ),
    ]
